routes/contract.py
from utils.db import db
from datetime import date
from flask import Blueprint, render_template, request, redirect, url_for, flash
from Models.models import Contract, Employee, Project

from RabbitMQ.rabbit import Rabbit
import json


contracts = Blueprint('contracts', __name__)

rabbit = Rabbit()

@contracts.route("/contracts/<employee_id>", methods=["GET"])
def index(employee_id):
    employee = Employee.query.get(employee_id)
    projects = Project.query.all()
    return render_template("contracts.html", employee=employee.to_json(), projects=projects)


@contracts.route("/contracts/hire/", methods=["POST", "GET"])
def hire():

    if request.method == 'POST':

        employee_id = request.form.get("employee_id")
        employee = Employee.query.get(employee_id)
        if not employee:
            return redirect(url_for('/'))

        project_id = request.form.get("project_id")
        project = Project.query.get(project_id)
        if not project:
            flash("No hay proyectos.", "warning")
            return redirect(url_for("contracts.index", employee_id=employee_id))

        # que que no haya mas de un contracto activo
        # en el mismo proyecto

        active_projects = Contract.query.filter_by(project_id=project_id, employee_id=employee_id, state="active")
        if active_projects.first():
            projects = [c.project for c in active_projects]
            flash(f"{employee.name} ya cuenta con un contrato activo en {projects[0]['name']}", 'warning')
            return redirect(url_for("contracts.index", employee_id=employee.id))

        new_contract = Contract(
            salary=request.form.get("salary"),
            project_id=project_id,
            employee_id=employee_id
        )

        db.session.add(new_contract)
        db.session.commit()

        rabbit.publish(message=json.dumps(new_contract.to_json()), exchange="HHRR")

        flash("Trabajador contratado exitosamente!", "info")
        return redirect(url_for("contracts.index", employee_id=employee_id))


@contracts.route("/contracts/fire/<int:employee_id>", methods=["POST"])
def fire(employee_id):
    if request.method == "POST":
        contract_id = request.form.get("contract_id")
        contract = Contract.query.get(contract_id)
        if not contract:
            flash('No hay contratos', 'warning')
            return redirect(url_for('contracts.index', employee_id=employee_id))

        contract.state = "inactive"
        contract.end_date = date.today()

        db.session.commit()

        # TODO: Publish a queue for rabbitMQ
        rabbit.publish(message=json.dumps(contract.to_json()), exchange="HHRR")

        # Exchange RRHH_fire, send project, salary
        flash("Trabajador desvinculado exitosamente!", "info")
        return redirect(url_for("contracts.index", employee_id=contract.employee_id))

routes/employee.py
from utils.db import db
from utils.validate import validate_run

from flask import Blueprint, render_template, redirect, \
    request, flash, url_for
from Models.models import Employee

employees = Blueprint('employees', __name__)


@employees.route('/new', methods=['POST'])
def store():
    if request.method == 'POST':
        rut = validate_run(request.form.get("rut"))
        if not rut:
            flash('Rut del trabajador inválido', 'warning')
            return redirect(url_for('index'))

        employee = Employee.query.filter_by(rut=rut).first()
        if employee:
            flash('El trabajador ya existe', 'warning')
            return redirect(url_for('index'))

        new_employee = Employee(
            rut=rut,
            name=request.form.get("name")
        )

        db.session.add(new_employee)
        db.session.commit()

        flash('Trabajador añadido exitosamente!', 'info')

        return redirect(url_for('index'))


@employees.route("/update/<int:employee_id>", methods=["GET", "POST"])
def update(employee_id):
    employee = Employee.query.get(employee_id)

    if request.method == "POST":

        name = request.form.get("name")

        if name != employee.name:
            employee.name = name
            db.session.commit()
            flash('Trabajador actualizado exitosamente!', 'info')

    return render_template("update.html", employee=employee, contracts=employee.contracts)


@employees.route("/delete/<int:employee_id>", methods=["GET"])
def delete(employee_id):
    employee = Employee.query.get(employee_id)

    db.session.delete(employee)
    db.session.commit()

    flash('Trabajador eliminado exitosamente!', 'info')

    return redirect(url_for('index'))

routes/format.py
from flask import Blueprint, jsonify, request, make_response
from utils.format import format_currency

format = Blueprint('format', __name__)


@format.route('/', methods=['POST'])
def format_default():
    elements = request.json.get("elements")
    for i in range(len(elements)):
        elements[i]["value"] = format_currency(elements[i]["value"])
    return make_response(jsonify(elements))

templates/partials/forms/Form.html
<div class="card-body .w-100">
    <div class="bg-black text-light p-3">
        <form class="card bg-black text-light"
            action="{% block form_url %}{% endblock %}"
            method="POST"
                    >
            {% block form %}

            {% endblock %}
        </form>

    </div>
</div>

<script>
  format_numbers_url = "{{url_for('format.format_default')}}"
</script>
<script src="{{url_for('static', filename='js/ajax.js')}}"></script>

templates/partials/forms/_AddEmployeeForm.html
{% extends 'partials/forms/Form.html' %}
{% block form_url %}
/new
{% endblock %}
{% block form %}
<h1 class="h5 mb-4">Añadir Trabajador</h1>

<div class="mb-3">
  <label>Nombre:</label>
  <input
    type="text"
    name="name"
    class="form-control rounded-0 bg-dark border-0 text-white"
    placeholder="Nombre del trabajador"
    autofocus
    required
  />
</div>

<div class="mb-3">
  <label>Rut:</label>
  <input
    type="text"
    name="rut"
    class="form-control rounded-0 bg-dark border-0 text-white"
    placeholder="Rut del trabajador"
    required
  />
</div>


<button class="btn btn-primary">Guardar</button>
{% endblock %}

templates/partials/forms/_EditEmployeeForm.html
{% extends 'partials/forms/Form.html' %}
{% block form_url %}
{{url_for('employees.update', employee_id=employee.id)}}
{% endblock %}

{% block form %}
<h1 class="h5 mb-4">Trabajador</h1>

<div class="mb-3">
  <label>Nombre:</label>
  <input
    type="text"
    name="name"
    value="{{employee.name}}"
    class="form-control rounded-0 bg-dark border-0 text-white"
    autofocus
    required
  />
</div>

<div class="mb-3">
  <label>Rut:</label>
  <input
    type="text"
    name="rut"
    value="{{employee.rut}}"
    class="form-control rounded-0 bg-dark border-0 text-white"
        disabled
    required
  />
</div>
<div class="flexRow">
  <button class="btn btn-primary bg-dark md-2">Guardar</button>
  <div class=md-3">
    <a
      href="{{ url_for('contracts.index', employee_id=employee.id)}}"
      class="btn btn-warning form-control rounded-0 bg-dark  text-white">Ver Contratos</a>

  </div>
</div>
{% endblock %}

templates/partials/forms/_FireForm.html
{% extends 'partials/forms/Form.html' %}
{% block form_url %}
{{url_for('contracts.fire', employee_id=employee.id)}}
{% endblock %}

{% block form %}

<h1 class="h5 mb-4">Desvincular Trabajador</h1>

<div class="mb-3">
    <label>Nombre:</label>
    <input
            type="text"
            name="employee_name"
            class="form-control rounded-0 bg-dark border-0 text-white"
            value="{{employee.name}}"
            disabled

    />
</div>

<div class="mb-3">
    <label>Contratos:</label>
    <input
            name="contract_id"
            id="contract_id"
            disabled
            hidden
            required
    />
    <select name="contract_id"
            class="form-control projectSelect"
            {% if contracts %}
            selected="{{contracts.0.project_id}}"
            {% endif %}
    >

        {% for contract in employee.active_contracts %}
        <option
                value="{{contract.id}}"
        >{{contract.project.name}}</option>

        {% endfor %}
    </select>

</div>


<div class="flexRow">
    <div class="mb-3">
        <label >Sueldo total entre todos los proyectos:</label>
        <input
                type="text"
                name="total_salary"
                id="total_salary"
                class="form-control rounded-0 bg-dark border-0 text-white"
                disabled
                required
        />
    </div>
    <div class="mb-3">
        <label id="salary_lbl">Sueldo en el proyecto: </label>
        <input
                type="text"
                id="contract_salary"
                name="contract_salary"
                class="form-control rounded-0 bg-dark border-0 text-white"
                disabled
                required
        />

    </div>
</div>
<button class="btn btn-danger unlink">Desvincular</button>
{% block script %}

<script>
    // retrieve data from flask template
    const contracts = JSON.parse('{{ employee.active_contracts|tojson }}');
    const employee = JSON.parse('{{ employee|tojson }}');

</script>
<script src="{{url_for('static', filename='js/FireForm.js')}}"></script>

{% endblock %}
{% endblock %}

templates/partials/forms/_HireForm.html
{% extends 'partials/forms/Form.html' %}
{% block form_url %}
{{url_for('contracts.hire')}}
{% endblock %}
{% block form %}

<h1 class="h5 mb-4">Contratar Trabajador</h1>

<div class="mb-3">
  <input
    type="text"
    name="employee_id"
    value="{{employee.id}}"
    class="form-control rounded-0 bg-dark border-0 text-white"
    hidden
    required
  />
  <label >Nombre:</label>
  <input
    type="text"
    name="name"
    value="{{employee.name}}"
    class="form-control rounded-0 bg-dark border-0 text-white"
    placeholder="Nombre del trabajador"
    disabled
    required
  />
</div>
<div class="mb-3">
  <label >Proyecto:</label>

  <select
    name="project_id"
    class="form-control"  >
    {% for project in projects %}
      <option value="{{project.id}}">{{project.name}}</option>
    {% endfor %}
  </select>
</div>

<div class="mb-3">
  <label >Sueldo:</label>
  <input
    type="number"
    name="salary"
    id="salary"
    class="form-control rounded-0 bg-dark border-0 text-white"
    required
  />
</div>

<button class="btn btn-primary">Contratar</button>

{% endblock %}