routes/employee.py
from utils.db import db
from utils.validate import validate_run

from flask import Blueprint, render_template, redirect, \
    request, flash, url_for
from Models.models import Employee

employees = Blueprint('employees', __name__)


@employees.route('/new', methods=['POST'])
def store():
    if request.method == 'POST':
        rut = validate_run(request.form.get("rut"))
        if not rut:
            flash('Rut del trabajador inválido', 'warning')
            return redirect(url_for('index'))

        employee = Employee.query.filter_by(rut=rut).first()
        if employee:
            flash('El trabajador ya existe', 'warning')
            return redirect(url_for('index'))

        new_employee = Employee(
            rut=rut,
            name=request.form.get("name")
        )

        db.session.add(new_employee)
        db.session.commit()

        flash('Trabajador añadido exitosamente!', 'info')

        return redirect(url_for('index'))


@employees.route("/update/<int:employee_id>", methods=["GET", "POST"])
def update(employee_id):
    employee = Employee.query.get(employee_id)

    if request.method == "POST":

        name = request.form.get("name")

        if name != employee.name:
            employee.name = name
            db.session.commit()
            flash('Trabajador actualizado exitosamente!', 'info')

    return render_template("update.html", employee=employee, contracts=employee.contracts)


@employees.route("/delete/<int:employee_id>", methods=["GET"])
def delete(employee_id):
    employee = Employee.query.get(employee_id)

    db.session.delete(employee)
    db.session.commit()

    flash('Trabajador eliminado exitosamente!', 'info')

    return redirect(url_for('index'))

templates/elements/ContractCell.html
<div class="card card-body bg-dark text-white flexRow">
    <tr><h6>
        Sueldo
        <input
      type="text"
      name="salary"
      value="{{format_currency(contract.salary)}}"
      class="form-control bg-dark text-white rounded-0"
      disabled
    />
    </h6>
    <h6>
        Proyecto
        <input
      type="text"

      value="{{contract.project.name}}"
      class="form-control bg-dark text-white rounded-0"
      disabled
        />
    </h6>
    <h6>
        Estado
        <input
      type="text"
      name="state"
      value="{{contract.state}}"
      class="form-control bg-dark text-white rounded-0"
      disabled
    />
    </h6>

    <h6>
        Fecha de inicio
        <input
      type="text"

      value="{{contract.start_date}}"
      class="form-control bg-dark text-white rounded-0"
      disabled
        />
    </h6>

    <h6>
        Fecha de término
        <input
      type="text"

      value="{{contract.end_date}}"
      class="form-control bg-dark text-white rounded-0"
      disabled
        />
    </h6>
    </tr>
</div>

templates/elements/ContractList.html
<div class="flexRow">
    <div class="flexColumn card mb-1 bg-black text-white">

        {% set this_contracts = contracts %}
        {% set header = "Contratos" %}

        {% if projects %}
          {% set this_contracts = employee.active_contracts %}
          {% set header = "Contratos activos de " + employee.name %}
        {% endif %}
        <div>
           <h1 class="h5 mb-6">{{header}}</h1>
        </div>

        <div>
            {% for contract in this_contracts %}
                {% include 'elements/ContractCell.html' %}
            {% endfor %}
        </div>

    </div>
</div>

templates/elements/EmployeeCell.html
<div class="card mb-1 bg-black text-white">
  <div class="card-body py-2 px-3">
    <div class="d-flex justify-content-between">
      <h5 class="card-title h6">{{ employee.name}}</h5>
      <div>
        <a href="{{ url_for('employees.update', employee_id=employee.id) }}" class="btn btn-dark btn-sm rounded-0">Editar</a>
        <a href="{{ url_for('employees.delete', employee_id=employee.id) }}" class="btn btn-danger btn-sm rounded-0">Borrar</a>
      </div>
    </div>
    <p class="card-text">{{ employee.rut }}</p>
  </div>
</div>